name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest


    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: bodakyuriy
          password: dckr_pat_siks_ZXn0JPEc3bGBtQhqrc8cJI
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: ./docker/php/Dockerfile
          push: true
          target: final
          tags: bodakyuriy/ticket-state-machine:latest
